export const vrsteJelaLista = [
  "Američka kuhinja",
  "BBQ",
  "Doručak",
  "Burgeri",
  "Kava",
  "Kineska kuhinja",
  "Deserti",
  "Francuska kuhinja",
  "Grčka kuhinja",
  "Zdrava hrana",
  "Indijska kuhinja",
  "Talijanska kuhinja",
  "Japanska kuhinja",
  "Meksička kuhinja",
  "Nudle",
  "Organska hrana",
  "Pasta",
  "Pizza",
  "Saladte",
  "Morska hrana",
  "Španjolska kuhinja",
  "Steak",
  "Sushi",
  "Tacosi",
  "Veganska hrana",
  "Alkohol",
  "Pića"
]